title: Birendra Kathariya
logo: /assets/img/logo.jpg
email: bkkvh8 at umstem dot edu
theme: jekyll-theme-minimal
blank_title: true
favicon: true
description: ""
show_downloads: false
color-scheme: light
